CREATE TABLE [dbo].[tblCaixaMovFormaTipo](
	[IDMovTipo] [smallint] IDENTITY(1,1) NOT NULL,
	[MovTipo] [varchar](50) NOT NULL,
	[Ativo] [bit] NOT NULL,
 CONSTRAINT [PK_tblCaixaMovFormaTipo] PRIMARY KEY CLUSTERED 
(
	[IDMovTipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_tblCaixaMovFormaTipo] UNIQUE NONCLUSTERED 
(
	[MovTipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[tblCaixaMovFormaTipo] ADD  CONSTRAINT [DF_tblCaixaMovFormaTipo_Ativo]  DEFAULT ((-1)) FOR [Ativo]
GO


